---
abstract: 'Like DBIC TimeStamp but in HiRes'
author:
  - 'John Judd <funkyshu@dark-linux.com>'
build_requires:
  Test::More: 0.98
  Test::Perl::Critic: 1.02
  version: 0.88
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-TimeStamp-HiRes
provides:
  DBIx::Class::TimeStamp::HiRes:
    file: lib/DBIx/Class/TimeStamp/HiRes.pm
    version: v1.0.0
requires:
  DBIx::Class::TimeStamp: 0
  DateTime::HiRes: 0
  version: 0.77
resources:
  license: http://dev.perl.org/licenses/
version: v1.0.0
